name: local_storage_plants_api
description: A Flutter implementation of the PlantsApi that uses local storage.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.3.0

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.3.0
  rxdart: ^0.27.2
  shared_preferences: ^2.0.7
  plants_api:
    path: ../plants_api

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0

